spring:
  application:
    name: processo
  datasource:
    url: jdbc:h2:~/data/SBanco
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
  flyway:
    enabled: true
    url: jdbc:h2:~/data/SBanco
    baseline-on-migrate: true
    user: sa
    password: password
    driverClassName:  org.h2.Driver
    clean-disabled: true
    locations: classpath:db.migration
    encoding: UTF-8
    outOfOrder: false
    schemas: public
    validate-on-migrate: true
  h2:
    console:
      enabled: true
  profiles:
    active: ${SERVER_ENV:local}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20000
  data:
    mongodb:
      database: SBanco
      uri: mongodb://mongodb:27017/SBanco?maxPoolSize=50&waitQueueTimeoutMS=2000
      auto-index-creation: true
  kafka:
    producer:
      buffer-memory: 31457280
      message-max-bytes: 31457280
      max-request-size: 31457280
      bootstrap-servers: broker1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max:
          request:
            size: 31457280
    consumer:
      bootstrap-servers: broker1:9092
      group-id: group-id-crud-usuario
      auto-offset-reset: earliest
      message-max-bytes: 31457280
      max-partition-fetch-bytes: 31457280
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
crud:
  kafka:
    listen:
      auto:
        start: true

h2-server:
  port: 8081

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs